version: '3'


services:
  postgres:
    image: postgres
    container_name: barbershop   
    environment:
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
    volumes:
      - ./.posgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
